name: Automate Repository

on:
  push:
    paths:
      - "*.ts"
  workflow_dispatch:

jobs:
  auto:
    runs-on: ubuntu-latest
    name: "Automate Repository"

    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Update README and related files
        run: deno run --allow-read --allow-write --allow-env --allow-net --allow-run calculate.ts
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Format Languages.ts
        run: deno fmt Languages.ts

      - name: Commit changes
        run: |
          git config --global user.avatar https://i.imgur.com/FpGl7KO.png
          git config --global user.name "Venoxity Official Bot"
          git config --global user.email "contact@venoxity.dev"
          git add "*.md" "*.js" "*.ts" "Languages.ts"
          git commit -m "chore: update files" || true
          git push || true
