name: Automate Repository

on:
  push:
    paths:
      - "*.ts"
  workflow_dispatch:

jobs:
  auto:
    runs-on: ubuntu-latest
    name: "Automate Repository"

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Update README
        run: deno run --allow-read --allow-write --allow-env --allow-net calculate.ts
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add verified.js incomplete.js README.md
          git commit -m "Update verified.js and incomplete.js"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
