name: Automate Repository

on:
  push:
    paths:
      - "*.ts"
  workflow_dispatch:

jobs:
  auto:
    runs-on: ubuntu-latest
    name: "Automate Repository"

    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Update README
        run: deno run --allow-read --allow-write --allow-env --allow-net calculate.ts
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          add: "*.md, *.js"
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          author_name: Venoxity Development
          author_email: contact@venoxity.dev
          message: "chore: re-generate README"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
