name: Automate Repository

on:
  push:
    paths:
      - "*.ts"
  workflow_dispatch:

jobs:
  auto:
    runs-on: ubuntu-latest
    name: "Automate Repository"

    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Update README, and related files
        run: deno run --allow-read --allow-write --allow-env --allow-net --allow-run calculate.ts
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Commit changes
        run: |
          git config --global user.name "Venoxity Official Bot"
          git config --global user.email "contact@venoxity.dev"
          git add "*.md *.js *.ts"
          git commit -m "chore: re-generate README and related files" || true
          git push || true

      - name: Format Languages.ts
        run: |
          deno fmt Languages.ts
          const formattedContent = await Deno.readTextFile("Languages.ts");
          await Deno.writeTextFile("Languages.ts", formattedContent)

      - name: Commit formatted Languages.ts
        run: |
          git add Languages.ts
          git commit -m "chore: format Languages.ts" || true
          git push || true
